spring:
  application:
    name: forum-service
  config:
    import: "consul:"
  cloud:
    consul:
      host: 192.168.100.6
      port: 30580
      config:
        format: YAML
        data-key: data
        fail-fast: true
      discovery:
        healthCheckPath: ${server.servletPath}/actuator/health
        healthCheckInterval: 15s

server:
  servlet:
    context-path: /forum-service