spring:
  application:
    name: forum-service

  cloud:
    consul:
      config:
        format: YAML
        data-key: data
        fail-fast: true
      discovery:
        healthCheckPath: ${server.servletPath}/actuator/health
        healthCheckInterval: 15s

server:
  servlet:
    context-path: /forum-service