spring:
  application:
    name: search-service

  elasticsearch:
    uris: ${ELK_URI}

  cloud:
    consul:
      host: 192.168.100.6
      port: 30080
      discovery:
        #        register-health-check: false
        heartbeat:
          enabled: true
          ttl: 10s

  
  kafka:
    template:
      default-topic: forum-dev
    producer:
      bootstrap-servers: 192.168.100.6:30005
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    consumer:
      bootstrap-servers: 192.168.100.6:30005
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: search-service
      properties:
        spring.json.trusted.packages: com.pashynski.shared.kafka
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

#management:
#  server:
#    port: 4452
#  endpoints:
#    web:
#      exposure:
#        include: health,info  # Or "*" for all endpoints
#    endpoint:
#      health:
#        enabled: true
#        show-details: always
server:
  port: 8081
  servlet:
    context-path: /search-service