spring:
  application:
    name: forum

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://alex-pash.ddns.net/keycloak/realms/forum-dev/protocol/openid-connect/certs

  datasource:
    url: "jdbc:postgresql://${PG_DB_HOST}:${PG_DB_PORT}/${PG_DB_NAME}"
    driver-class-name: "org.postgresql.Driver"
    username: ${PG_DB_USERNAME}
    password: ${PG_DB_PASSWORD}

server:
  servlet:
    context-path: /forum-service

topics:
  max-page-size: 20
posts:
  max-page-size: 20

minio:
  url: http://192.168.100.6:30010
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: public